= Genies

This project uses Ollama, running in a Docker container, to manage self-hosted open source AI models like DeepSeek-V3/R1, Llama 3.3, and Qwen.

Ollama provides a convenient platform for running AI models locally, giving users privacy over the data they feed into the models, and allowing customization of models for specific use cases.

== Documentation

=== Prerequisites

* Docker

=== Usage

Make sure the "run" scripts are executable:

[source,bash]
----
chmod +x ./run/*
----

Start the Ollama service in a Docker container:

[source,bash]
----
./run/start
----

Stop it:

[source,bash]
----
./run/stop
----

Use `./run/ollama` to interact with Ollama inside the container. All arguments are passed  verbatim to the `ollama` command inside the container.

To pull a model:

* DeepSeek-V3/R1: `./run/ollama pull deepseek-r1`
* Llama 3.3: `./run/ollama pull llama3.3`
* Qwen: `./run/ollama pull qwen`

See https://ollama.com/library for the full model library.

To run a model:

[source,bash]
----
./run/ollama run llama3.3
----

List installed models:

[source,bash]
----
./run/ollama list
----

Access the API at `http://localhost:11434`.

''''

Copyright © 2026-present Kieran Potts, link:./LICENSE.txt[MIT license]
