= Usage

Make sure the "run" scripts are executable:

[source,bash]
----
chmod +x ./run/*
----

Start the Ollama service in a Docker container:

[source,bash]
----
./run/start
----

Stop it:

[source,bash]
----
./run/stop
----

Use `./run/ollama` to interact with Ollama inside the container. All arguments are passed verbatim to the `ollama` program, which runs in the container.

To pull a model:

[source,bash]
----
./run/ollama run <model-name>
----

Example:

[source,bash]
----
./run/ollama run llama3.3
----

See the documentation on link:./models.adoc[models] to learn about your choices.

List all the models you have installed:

[source,bash]
----
./run/ollama ls
----

To run a model:

[source,bash]
----
./run/ollama run llama3.3
----

This command starts Ollama's built-in chat interface, from where you interact with the model via a command line interface. It is a minimal interface, and by default the models do not have access to your filesystem or other external systems.

To do more with your models, like to use them as coding assistants, you will need a front-end. For example, to use your models as coding assistants, you will need to install a coding agent and configure your local model as the agent's back-end. See the documentation on link:./front-ends.adoc[front-ends] for further information.

More CLI commands are available for Ollama - see https://docs.ollama.com/cli. You can also use https://docs.ollama.com/api/introduction[the API], served from `http://localhost:11434`, to integrate with Ollama programmatically from your own applications.
